[window]
decorations = "none" # hide title bar
startup_mode = "Maximized"


[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
bold = { style = "Bold" }
italic = { style = "Italic" }
bold_italic = { style = "Bold Italic" }
size = 10.5


[colors]

[colors.primary]
foreground = "#dcdccc"
background = "#282828"

[colors.normal]
black = "#3f3f3f"
red = "#cf5050"
green = "#60d48a"
yellow = "#dfaf8f"
blue = "#94bff3"
magenta = "#dc8cc3"
cyan = "#8cd0d3"
white = "#dcdccc"

[colors.bright]
black = "#709080"
red = "#fca3a3"
green = "#84e5a3"
yellow = "#f0dfaf"
blue = "#9ab8d7"
magenta = "#ec93d3"
cyan = "#93e0e3"
white = "#ffffff"


[keyboard]
bindings = [
  { key = "T", mods = "Control|Shift", action = "SpawnNewInstance" }
]
